import { describe, expect, it } from "vitest";

import { supersededEntries } from "./decisions-file.js";
import { planExport } from "./export.js";
import type { DecisionView } from "./tree.js";

const HEADER = [
  "# Decisions: Simpler API error responses",
  "",
  "Generated by the Grill Room export from this session's settled design tree.",
  "",
  "## Decisions",
  "",
].join("\n");

function entry(
  key: string,
  title: string,
  fields: string[],
): string {
  return [`<a id="${key}"></a>`, `### ${title}`, "", ...fields].join("\n");
}

describe("supersededEntries", () => {
  it("returns nothing for a decisions.md with no entries", () => {
    expect(supersededEntries(`${HEADER}\n`)).toEqual([]);
  });

  it("skips an entry with no Supersedes line", () => {
    const text = `${HEADER}${entry("reconcile", "Reconcile the idea", [
      "- **Decision:** Scoped override",
      "- **Origin:** interviewer · accepted recommendation",
    ])}\n`;
    expect(supersededEntries(text)).toEqual([]);
  });

  it("finds the one entry that carries Supersedes, with its key, title and Source citation", () => {
    const text = `${HEADER}${entry("rfc7807-problem-details-for-all-errors", "RFC 7807 Problem Details for all error responses", [
      "- **Decision:** The workout complete and uncomplete endpoints return errors as a flat JSON body.",
      "- **Origin:** repo (recorded) · reopened",
      "- **Source:** docs/adr/003-rfc7807-problem-details.md:19",
      '- **Supersedes:** "We will use RFC 7807 Problem Details for all error responses."',
    ])}\n`;

    expect(supersededEntries(text)).toEqual([
      {
        key: "rfc7807-problem-details-for-all-errors",
        title: "RFC 7807 Problem Details for all error responses",
        source: "docs/adr/003-rfc7807-problem-details.md:19",
      },
    ]);
  });

  it("finds several entries, only those with Supersedes, among ones without it", () => {
    const text = [
      HEADER,
      entry("reconcile-flat-error-with-adrs", "Reconcile the flat error idea with the ADRs", [
        "- **Decision:** Scoped override",
        "- **Origin:** interviewer · accepted recommendation",
      ]),
      "",
      entry("rfc7807-problem-details-for-all-errors", "RFC 7807 Problem Details for all error responses", [
        "- **Decision:** Flat body for complete/uncomplete only.",
        "- **Origin:** repo (recorded) · reopened",
        "- **Source:** docs/adr/003-rfc7807-problem-details.md:19",
        '- **Supersedes:** "We will use RFC 7807 Problem Details for all error responses."',
      ]),
      "",
      entry("hateoas-scoped-override", "HATEOAS links on these endpoints", [
        "- **Decision:** Drop _links entirely for these two endpoints.",
        "- **Origin:** repo (recorded) · reopened",
        "- **Source:** docs/adr/002-hateoas-hypermedia.md:19",
        '- **Supersedes:** "We will implement HATEOAS with _links objects in all resource responses."',
      ]),
      "",
      entry("toast-component-choice", "How should the frontend surface the error message?", [
        "- **Decision:** Install a toast library.",
        "- **Origin:** interviewer · another offered option",
      ]),
      "",
    ].join("\n");

    expect(supersededEntries(text)).toEqual([
      {
        key: "rfc7807-problem-details-for-all-errors",
        title: "RFC 7807 Problem Details for all error responses",
        source: "docs/adr/003-rfc7807-problem-details.md:19",
      },
      {
        key: "hateoas-scoped-override",
        title: "HATEOAS links on these endpoints",
        source: "docs/adr/002-hateoas-hypermedia.md:19",
      },
    ]);
  });

  it("reads a Source citation that is a line range", () => {
    const text = `${HEADER}${entry("problem-catalog-scoped", "The problem type catalog for these endpoints", [
      "- **Decision:** Only two entries remain in the catalog for the flat-error endpoints.",
      "- **Origin:** repo (recorded) · reopened",
      "- **Source:** docs/adr/003-rfc7807-problem-details.md:104-112",
      '- **Supersedes:** "The project defines specific problem type URIs mapped to HTTP statuses."',
    ])}\n`;

    expect(supersededEntries(text)).toEqual([
      {
        key: "problem-catalog-scoped",
        title: "The problem type catalog for these endpoints",
        source: "docs/adr/003-rfc7807-problem-details.md:104-112",
      },
    ]);
  });

  it("ignores the Superseded by and Settled by lines an accepted replacement writes", () => {
    const text = [
      HEADER,
      entry("storage", "Where does the data live?", [
        "- **Decision:** On disk",
        "- **Origin:** interviewer · accepted recommendation",
        "- **Superseded by:** [Which disk does the data live on?](#storage-location): The data moved to a synced folder.",
        "- **Settled by:** `repo-stack`",
        // Not a line the renderer writes without Supersedes: here only to show
        // that Superseded by alone never marks an entry.
        "- **Source:** docs/adr/001-storage.md:3",
      ]),
      "",
      entry("repo-db", "Move to Postgres", [
        "- **Decision:** Postgres",
        "- **Origin:** repo (inferred) · reopened",
        "- **Superseded by:** `hosting`: Hosted elsewhere.",
        "- **Settled by:** [Where does the data live?](#storage)",
        "- **Source:** server/db/index.ts:4",
        '- **Supersedes:** "SQLite."',
      ]),
      "",
    ].join("\n");

    expect(supersededEntries(text)).toEqual([
      { key: "repo-db", title: "Move to Postgres", source: "server/db/index.ts:4" },
    ]);
  });

  it("ignores fields other than Source and Supersedes", () => {
    const text = `${HEADER}${entry("adr-amendment-scope", "Should the scoped exception be written down?", [
      "- **Decision:** No edits to the ADR.",
      "- **Origin:** interviewer · own answer",
      "- **Depends on:** [Reconcile the flat error idea](#reconcile-flat-error-with-adrs)",
    ])}\n`;
    expect(supersededEntries(text)).toEqual([]);
  });
});

describe("supersededEntries with ADR fields", () => {
  function rendered(adrWorthy: boolean): string {
    const reopened: DecisionView = {
      id: "id-rfc",
      key: "rfc",
      questionTitle: "RFC",
      questionBody: "",
      choices: [],
      recommendedChoice: null,
      recommendedChoiceLabel: null,
      recommendedAnswer: "Flat body",
      dependsOn: [],
      state: "settled",
      supersession: null,
      deferralReason: null,
      restatementText: null,
      restatementNotes: null,
      restatementReason: null,
      replacedBy: null,
      settledBy: null,
      dispositionTarget: null,
      settledAt: "2026-09-01T00:00:00.000Z",
      reopenedAt: null,
      withdrawnAt: null,
      awaitingPlacementSince: null,
      createdAt: "2026-09-01T00:00:00.000Z",
      ...{
        introducedBy: "repo",
        repo: {
          source: "recorded",
          citation: "docs/adr/003-x.md:19",
          statement: "We will use RFC 7807.",
          scoutReportId: "report-1",
        },
        answer: { text: "Flat body", kind: "own-answer" },
        adrWorthy,
        consequences: "Commits us.\n- **Source:** x",
      },
    };
    const plan = planExport({
      history: {},
      sessionTitle: "Simpler API error responses",
      idea: "An idea.",
      specMarkdown: "## Problem\n\nA spec.",
      tickets: [],
      decisions: [reopened],
      readiness: null,
      scoutReport: null,
    });
    return plan.files.find((file) => file.relativePath === "decisions.md")!.content;
  }

  it("a file with ADR fields gives the same superseded entries", () => {
    const flagged = rendered(true);
    expect(flagged).toContain("- **ADR-worthy:** yes");
    expect(flagged).toContain("  - **Source:** x");
    expect(rendered(false)).not.toContain("ADR-worthy");
    expect(supersededEntries(flagged)).toEqual(supersededEntries(rendered(false)));
    expect(supersededEntries(flagged)).toHaveLength(1);
  });
});
