import { eq } from "@agent-native/core/db/schema";
import { describe, expect, it } from "vitest";

import { createHash } from "node:crypto";

import acceptRestatement from "../actions/accept-restatement.js";
import createSession from "../actions/create-session.js";
import { getDb, schema, useTestDatabase } from "../test/db.js";
import {
  buildExportManifest,
  extractSpecSection,
  hashExportContent,
  parseExportManifest,
  planExport,
  renderExportManifest,
} from "./export.js";
import type { StoredReadiness } from "./readiness.js";
import type { ScoutReportWithStaleness } from "./scout-report.js";
import { describeDecisions, type DecisionView } from "./tree.js";

let counter = 0;

/** A settled interviewer decision answered with its recommendation, unless told otherwise. */
function decision(key: string, overrides: Partial<DecisionView> = {}): DecisionView {
  counter += 1;
  return {
    id: `id-${key}`,
    key,
    questionTitle: `Title of ${key}`,
    questionBody: `The question behind ${key}, which never reaches decisions.md.`,
    choices: [],
    recommendedChoice: null,
    recommendedChoiceLabel: null,
    recommendedAnswer: `Answer of ${key}`,
    dependsOn: [],
    introducedBy: "interviewer",
    repo: null,
    state: "settled",
    answer: { text: `Answer of ${key}`, kind: "accepted-recommendation" },
    supersession: null,
    deferralReason: null,
    restatementText: null,
    restatementNotes: null,
    restatementReason: null,
    replacedBy: null,
    settledBy: null,
    adrWorthy: false,
    consequences: null,
    dispositionTarget: null,
    settledAt: "2026-09-01T00:00:00.000Z",
    reopenedAt: null,
    withdrawnAt: null,
    awaitingPlacementSince: null,
    createdAt: `2026-09-01T00:00:${String(counter % 60).padStart(2, "0")}.000Z`,
    ...overrides,
  };
}

function keptRepo(key: string, citation: string, source: "recorded" | "inferred" = "recorded") {
  return decision(key, {
    introducedBy: "repo",
    answer: { text: `Statement of ${key}`, kind: "repo-established" },
    repo: { source, citation, statement: `Statement of ${key}`, scoutReportId: "report-1" },
  });
}

function outOfScope(key: string, note: string, overrides: Partial<DecisionView> = {}) {
  return decision(key, {
    answer: { text: note, kind: "dispositioned" },
    dispositionTarget: "out-of-scope",
    ...overrides,
  });
}

function openQuestion(key: string) {
  return decision(key, {
    answer: { text: "Revisit once usage data exists.", kind: "dispositioned" },
    dispositionTarget: "open-question",
  });
}

function decisionsFile(decisions: readonly DecisionView[], sessionTitle = "Grill Room"): string | undefined {
  const plan = planExport({
    sessionTitle,
    idea: "An idea.",
    specMarkdown: "## Problem\n\nA spec.",
    tickets: [],
    decisions,
    readiness: null,
    scoutReport: null,
  });
  return plan.files.find((file) => file.relativePath === "decisions.md")?.content;
}

const CHOICES = [
  { label: "SQLite", rationale: "One file, no server to run." },
  { label: "Postgres", rationale: "Scales, but needs a server." },
];

describe("planExport: decisions.md", () => {
  it("renders the full file: header, entries with origin labels and the why, out of scope and built under", () => {
    const content = decisionsFile([
      keptRepo("repo-stack", "AGENTS.md:12"),
      decision("storage", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite",
        answer: { text: "SQLite", kind: "accepted-recommendation" },
        dependsOn: ["id-repo-stack"],
      }),
      decision("hosting", {
        choices: CHOICES,
        recommendedChoice: 0,
        answer: { text: "Postgres", kind: "own-answer" },
        dependsOn: ["id-storage", "id-metrics"],
      }),
      openQuestion("metrics"),
      decision("naming", {
        introducedBy: "user",
        choices: CHOICES,
        answer: { text: "Call it Grill Room,\nnot Grillr.", kind: "own-answer" },
        dependsOn: ["id-storage"],
      }),
      outOfScope("mobile", "Desktop only for now."),
    ]);

    expect(content).toBe(
      [
        "# Decisions: Grill Room",
        "",
        "Generated by the Grill Room export from this session's settled design tree.",
        "",
        "## Decisions",
        "",
        '<a id="storage"></a>',
        "### Title of storage",
        "",
        "- **Decision:** SQLite",
        "- **Why (interviewer's case):** One file, no server to run.",
        "- **Origin:** interviewer · accepted recommendation",
        "- **Depends on:** `repo-stack` (AGENTS.md:12)",
        "",
        '<a id="hosting"></a>',
        "### Title of hosting",
        "",
        "- **Decision:** Postgres",
        "- **Why (interviewer's case):** Scales, but needs a server.",
        "- **Origin:** interviewer · another offered option",
        "- **Depends on:** Title of metrics (open question, see spec), [Title of storage](#storage)",
        "",
        '<a id="naming"></a>',
        "### Title of naming",
        "",
        "- **Decision:** Call it Grill Room,",
        "  not Grillr.",
        "- **Origin:** user · own answer",
        "- **Depends on:** [Title of storage](#storage)",
        "",
        "## Out of scope",
        "",
        "- **Title of mobile**: Desktop only for now.",
        "",
        "## Built under",
        "",
        "- `repo-stack`: AGENTS.md:12",
        "",
      ].join("\n"),
    );
  });

  it("renders an accepted recommendation with a choice index as that choice, its case and the interviewer's note", () => {
    const content = decisionsFile([
      decision("accepted", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite, because one file is enough.",
        answer: { text: "SQLite, because one file is enough.", kind: "accepted-recommendation" },
      }),
      decision("same", {
        choices: CHOICES,
        recommendedChoice: 1,
        recommendedAnswer: "Postgres",
        answer: { text: "Postgres", kind: "accepted-recommendation" },
      }),
    ])!;

    expect(content).toContain(
      [
        '<a id="accepted"></a>',
        "### Title of accepted",
        "",
        "- **Decision:** SQLite",
        "- **Why (interviewer's case):** One file, no server to run.",
        "- **Recommendation note (interviewer's):** SQLite, because one file is enough.",
        "- **Origin:** interviewer · accepted recommendation",
      ].join("\n"),
    );
    // A note that only repeats the label adds nothing and is left out.
    expect(content).toContain(
      [
        "- **Decision:** Postgres",
        "- **Why (interviewer's case):** Scales, but needs a server.",
        "- **Origin:** interviewer · accepted recommendation",
      ].join("\n"),
    );
    expect(content.match(/Recommendation note/g)).toHaveLength(1);
  });

  it("renders an accepted recommendation without a choice index as its answer, with a why only on a text match", () => {
    const content = decisionsFile([
      decision("no-index", {
        choices: CHOICES,
        recommendedChoice: null,
        recommendedAnswer: "Keep it in memory.",
        answer: { text: "Keep it in memory.", kind: "accepted-recommendation" },
      }),
      decision("no-choices", {
        recommendedChoice: 0,
        answer: { text: "Ship weekly.", kind: "accepted-recommendation" },
      }),
      decision("matched", {
        choices: CHOICES,
        recommendedChoice: null,
        answer: { text: "SQLite", kind: "accepted-recommendation" },
      }),
    ])!;

    expect(content).toContain(
      "- **Decision:** Keep it in memory.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).toContain(
      "- **Decision:** Ship weekly.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).toContain(
      "- **Decision:** SQLite\n- **Why (interviewer's case):** One file, no server to run.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).not.toContain("Recommendation note");
  });

  it("labels an own answer that matches an offered choice as another offered option, with its case", () => {
    const content = decisionsFile([
      decision("picked", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite, because one file is enough.",
        answer: { text: "Postgres", kind: "own-answer" },
      }),
      decision("typed", { choices: CHOICES, answer: { text: "Flat JSON files", kind: "own-answer" } }),
    ])!;

    expect(content).toContain(
      "- **Decision:** Postgres\n- **Why (interviewer's case):** Scales, but needs a server.\n- **Origin:** interviewer · another offered option",
    );
    expect(content).toContain("- **Decision:** Flat JSON files\n- **Origin:** interviewer · own answer");
    expect(content).not.toContain("Recommendation note");
    expect(content).not.toContain("SQLite, because");
  });

  it("writes a reopened repo decision as a full entry with its source and a Supersedes line", () => {
    const content = decisionsFile([
      decision("repo-db", {
        introducedBy: "repo",
        answer: { text: "Move to Postgres.", kind: "own-answer" },
        repo: {
          source: "inferred",
          citation: "server/db/index.ts:4",
          statement: "The app stores\nits data in SQLite.",
          scoutReportId: "report-1",
        },
      }),
    ]);

    expect(content).toContain(
      [
        '<a id="repo-db"></a>',
        "### Title of repo-db",
        "",
        "- **Decision:** Move to Postgres.",
        "- **Origin:** repo (inferred) · reopened",
        "- **Source:** server/db/index.ts:4",
        '- **Supersedes:** "The app stores its data in SQLite."',
      ].join("\n"),
    );
    expect(content).not.toContain("## Built under");

    const recorded = decisionsFile([
      decision("repo-db", {
        introducedBy: "repo",
        answer: { text: "Move to Postgres.", kind: "accepted-recommendation" },
        repo: { source: "recorded", citation: "docs/adr/0001.md:3", statement: "SQLite.", scoutReportId: null },
      }),
    ]);
    expect(recorded).toContain("- **Origin:** repo (recorded) · reopened");
  });

  it("marks a replaced entry Superseded by its replacer, linked when the replacer is an entry, after Depends on and before the repo lines", () => {
    const content = decisionsFile([
      decision("shape"),
      decision("repo-db", {
        introducedBy: "repo",
        dependsOn: ["id-shape"],
        answer: { text: "Move to Postgres.", kind: "own-answer" },
        repo: { source: "inferred", citation: "server/db/index.ts:4", statement: "SQLite.", scoutReportId: null },
        replacedBy: { id: "id-location", key: "location", title: "Title of location", reason: "The data moved to a synced folder." },
      }),
      decision("location"),
    ])!;

    expect(content).toContain(
      [
        "- **Depends on:** [Title of shape](#shape)",
        "- **Superseded by:** [Title of location](#location): The data moved to a synced folder.",
        "- **Source:** server/db/index.ts:4",
        '- **Supersedes:** "SQLite."',
      ].join("\n"),
    );
    // The replaced entry stays an entry, in its usual place.
    expect(content).toContain('<a id="repo-db"></a>');
  });

  it("names a replacer that is not an entry by its key", () => {
    const content = decisionsFile([
      decision("storage", {
        replacedBy: { id: "id-gone", key: "gone", title: null, reason: "Moved." },
      }),
    ])!;

    expect(content).toContain("- **Superseded by:** `gone`: Moved.\n");
  });

  it("marks a settled loose end Settled by the decision that answered it, linked when that is an entry", () => {
    const content = decisionsFile([
      keptRepo("repo-stack", "AGENTS.md:12"),
      decision("shape"),
      decision("storage", {
        settledBy: { id: "id-shape", key: "shape", title: "Title of shape" },
      }),
      decision("hosting", {
        settledBy: { id: "id-repo-stack", key: "repo-stack", title: "Title of repo-stack" },
      }),
    ])!;

    expect(content).toContain(
      '<a id="storage"></a>\n### Title of storage\n\n- **Decision:** Answer of storage\n- **Origin:** interviewer · accepted recommendation\n- **Settled by:** [Title of shape](#shape)\n',
    );
    expect(content).toContain("- **Settled by:** `repo-stack`\n");
  });

  it("adds no line for a pending proposal, or when there is no link", () => {
    const plain = decisionsFile([decision("shape"), decision("storage")])!;
    const pending = decisionsFile([
      decision("shape"),
      decision("storage", {
        supersession: {
          kind: "replaces-settled",
          byId: "id-shape",
          byKey: "shape",
          byTitle: "Title of shape",
          answer: "",
          reason: "A guess.",
        },
      }),
    ])!;

    expect(plain).not.toContain("Superseded by");
    expect(plain).not.toContain("Settled by");
    expect(pending).toBe(plain);
  });

  it("lists a kept repo decision only under Built under, as key and citation, never restated", () => {
    const content = decisionsFile([keptRepo("repo-stack", "AGENTS.md:12"), decision("storage")])!;

    expect(content).toContain("## Built under\n\n- `repo-stack`: AGENTS.md:12\n");
    expect(content).not.toContain("Statement of repo-stack");
    expect(content).not.toContain('id="repo-stack"');
    expect(content).not.toContain("Title of repo-stack");
  });

  it("keeps a settled own answer whose deferral is only proposed as an entry", () => {
    const pending = decision("hold", {
      answer: { text: "Wait until dispute handling is settled", kind: "own-answer" },
      deferralReason: "The answer waits on dispute handling.",
    });

    const content = decisionsFile([pending])!;

    expect(content).toContain('<a id="hold"></a>');
    expect(content).toContain("Title of hold");
    expect(content).toContain("Wait until dispute handling is settled");
  });

  it("leaves out loose ends, open questions, and anything not settled, withdrawn or unplaced", () => {
    const left = [
      decision("unknown", { state: "frontier", answer: { text: "", kind: "unknown" } }),
      decision("pushed", { state: "frontier", answer: { text: "Wrong question", kind: "pushed-back" } }),
      decision("deferred", { state: "frontier", answer: { text: "", kind: "deferred" } }),
      decision("prototype", { state: "frontier", answer: { text: "Try it", kind: "prototype-flagged" } }),
      decision("never", { state: "frontier", answer: null }),
      decision("blocked", { state: "blocked", answer: null, dependsOn: ["id-never"] }),
      decision("stale", { state: "stale" }),
      decision("withdrawn", { state: "withdrawn" }),
      decision("unplaced", { state: "unplaced", introducedBy: "user", answer: null }),
      openQuestion("question"),
      outOfScope("stale-scope", "Stale note", { state: "stale" }),
    ];

    const content = decisionsFile([decision("kept"), ...left])!;

    for (const excluded of left) {
      expect(content).not.toContain(excluded.questionTitle);
    }
    expect(content).not.toContain("Revisit once usage data exists.");
    expect(content).not.toContain("## Out of scope");
    expect(content).toContain('<a id="kept"></a>');
    // A dropped repo decision never enters the tree, so it has nothing to render from.
  });

  it("orders every section topologically, prerequisites first, with ties broken by key", () => {
    const tree = [
      decision("zeta"),
      decision("alpha", { dependsOn: ["id-zeta"] }),
      decision("beta"),
      decision("gamma", { dependsOn: ["id-alpha", "id-beta"] }),
      outOfScope("z-scope", "Later."),
      outOfScope("a-scope", "Never.", { dependsOn: ["id-z-scope"] }),
      outOfScope("m-scope", "Not now."),
      keptRepo("repo-b", "b.md:1"),
      keptRepo("repo-a", "a.md:1"),
    ];

    const content = decisionsFile(tree)!;
    const anchors = [...content.matchAll(/<a id="([^"]+)"><\/a>/g)].map((match) => match[1]);
    expect(anchors).toEqual(["beta", "zeta", "alpha", "gamma"]);
    expect(content).toContain(
      "## Out of scope\n\n- **Title of m-scope**: Not now.\n- **Title of z-scope**: Later.\n- **Title of a-scope**: Never.\n",
    );
    expect(content).toContain("## Built under\n\n- `repo-a`: a.md:1\n- `repo-b`: b.md:1\n");

    expect(decisionsFile(tree)).toBe(content);
    expect(decisionsFile([...tree].reverse())).toBe(content);
  });

  it("links dependencies only to entries, and names out-of-scope ones in plain text", () => {
    const content = decisionsFile([
      outOfScope("mobile", "Desktop only."),
      decision("ui", { dependsOn: ["id-mobile", "id-gone", "id-missing"] }),
      decision("gone", { state: "withdrawn" }),
    ])!;

    expect(content).toContain("- **Depends on:** Title of mobile (out of scope)\n");
    expect(content).not.toContain("Title of gone");
    expect(content).not.toContain("](#mobile)");
  });

  it("plans decisions.md beside the spec with one entry, or with one out-of-scope item alone", () => {
    const withEntry = planExport({
      sessionTitle: "Grill Room",
      idea: "An idea.",
      specMarkdown: "A spec.",
      tickets: [{ number: 1, slug: "first", title: "First", body: "Body", blockedBy: [] }],
      decisions: [decision("only")],
      readiness: null,
      scoutReport: null,
    });
    expect(withEntry.files.map((file) => file.relativePath)).toEqual([
      "spec.md",
      "intent.md",
      "decisions.md",
      "issues/01-first.md",
    ]);

    const scopeOnly = decisionsFile([outOfScope("mobile", "")])!;
    expect(scopeOnly).toBe(
      [
        "# Decisions: Grill Room",
        "",
        "Generated by the Grill Room export from this session's settled design tree.",
        "",
        "## Out of scope",
        "",
        "- **Title of mobile**",
        "",
      ].join("\n"),
    );
    expect(scopeOnly).not.toContain("## Decisions\n");
  });

  it("does not plan decisions.md with only Built under, or with nothing", () => {
    expect(decisionsFile([keptRepo("repo-stack", "AGENTS.md:12")])).toBeUndefined();
    expect(decisionsFile([openQuestion("question")])).toBeUndefined();
    expect(decisionsFile([])).toBeUndefined();
  });
});

const IDEA = "Export an intent.md alongside the spec so a reader understands why the feature exists.";

function readinessJudgment(
  ideaJudged: string,
  overrides: Partial<StoredReadiness["result"]> = {},
): StoredReadiness {
  return {
    ideaJudged,
    result: {
      evidence: [],
      objective: "Write intent.md into every export bundle.",
      objectiveIsProcess: false,
      expectedOutcome: "A reader of the repo can see why the feature exists without opening Grill Room.",
      unknowns: [],
      verdict: "ready",
      missing: [],
      ...overrides,
    },
    judgedAt: "2026-09-01T00:00:00.000Z",
    scoutReportId: null,
  };
}

function scoutReportFixture(
  overrides: Partial<{
    currentState: ScoutReportWithStaleness["result"]["currentState"];
    commitRead: string | null;
    stale: boolean;
  }> = {},
): ScoutReportWithStaleness {
  const commitRead = overrides.commitRead === undefined ? "abc123" : overrides.commitRead;
  return {
    id: "report-1",
    sessionId: "session-1",
    projectId: "project-1",
    facts: {
      headCommit: commitRead,
      headBranch: "main",
      remotes: [],
      dirty: false,
      recentCommitSubjects: [],
      hasAgentInstructions: false,
      decisionsFolder: null,
      hasRulesFolder: false,
      decisionFiles: [],
      adrConvention: null,
    },
    result: {
      currentState: overrides.currentState ?? [
        {
          status: "built",
          summary: "The export bundle already writes decisions.md.",
          citations: ["server/export.ts:17"],
        },
        {
          status: "gap",
          summary: "Nothing records why a bundle exists.",
          citations: ["server/export-bundle.ts:1"],
        },
      ],
      proposedDecisions: [],
      previousDecisions: [],
    },
    commitRead,
    ideaRead: IDEA,
    model: "sonnet",
    ranAt: "2026-09-01T00:00:00.000Z",
    turnId: null,
    dispositions: {},
    stale: overrides.stale ?? false,
  };
}

function intentFile(
  input: {
    idea?: string;
    readiness?: StoredReadiness | null;
    scoutReport?: ScoutReportWithStaleness | null;
    specMarkdown?: string;
  } = {},
): string {
  const plan = planExport({
    sessionTitle: "Grill Room",
    idea: input.idea ?? IDEA,
    specMarkdown: input.specMarkdown ?? "## Problem\n\nA spec.",
    tickets: [],
    decisions: [],
    readiness: input.readiness ?? null,
    scoutReport: input.scoutReport ?? null,
  });
  return plan.files.find((file) => file.relativePath === "intent.md")!.content;
}

describe("planExport: intent.md", () => {
  it("renders the idea, readiness and project state when both are current — user evidence with no citation, repo evidence with one", () => {
    const content = intentFile({
      readiness: readinessJudgment(IDEA, {
        evidence: [
          { text: "The user said re-exports were silently destroying edits.", source: "idea", citation: null },
          {
            text: "The export bundle already writes decisions.md next to spec.md.",
            source: "repo",
            citation: "server/export.ts:17",
          },
        ],
        unknowns: ["Whether readers want a machine-readable format too."],
      }),
      scoutReport: scoutReportFixture(),
    });

    expect(content).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Judged at 2026-09-01T00:00:00.000Z, on the idea as first written, before any question was asked.",
        "",
        "- **Objective:** Write intent.md into every export bundle.",
        "- **Expected outcome:** A reader of the repo can see why the feature exists without opening Grill Room.",
        "- **Verdict:** ready",
        "",
        "**Evidence**",
        "",
        "- The user said re-exports were silently destroying edits. · the user said",
        "- The export bundle already writes decisions.md next to spec.md. · the repo shows (server/export.ts:17)",
        "",
        "**Unknowns**",
        "",
        "- Whether readers want a machine-readable format too.",
        "",
        "## Project state",
        "",
        "- **Built:** The export bundle already writes decisions.md. (server/export.ts:17)",
        "- **Gap:** Nothing records why a bundle exists. (server/export-bundle.ts:1)",
        "",
        "- **Commit read:** abc123",
        "",
      ].join("\n"),
    );
  });

  it("a not-ready verdict says the interview worked through what it lacked", () => {
    const notReadyContent = intentFile({
      readiness: readinessJudgment(IDEA, { verdict: "not-ready" }),
      scoutReport: null,
    });

    expect(notReadyContent).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Judged at 2026-09-01T00:00:00.000Z, on the idea as first written, before any question was asked.",
        "",
        "- **Objective:** Write intent.md into every export bundle.",
        "- **Expected outcome:** A reader of the repo can see why the feature exists without opening Grill Room.",
        "- **Verdict:** not-ready",
        "",
        "The interview that followed worked through what this judgment lacked; decisions.md and spec.md hold the result.",
        "",
      ].join("\n"),
    );

    const readyContent = intentFile({ readiness: readinessJudgment(IDEA), scoutReport: null });
    expect(readyContent).not.toContain(
      "The interview that followed worked through what this judgment lacked; decisions.md and spec.md hold the result.",
    );
  });

  it("reads exactly 'Not judged for this version of the idea.' when there is no readiness judgment", () => {
    const content = intentFile({ readiness: null, scoutReport: scoutReportFixture() });

    expect(content).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Not judged for this version of the idea.",
        "",
        "## Project state",
        "",
        "- **Built:** The export bundle already writes decisions.md. (server/export.ts:17)",
        "- **Gap:** Nothing records why a bundle exists. (server/export-bundle.ts:1)",
        "",
        "- **Commit read:** abc123",
        "",
      ].join("\n"),
    );
  });

  it("reads exactly 'Not judged for this version of the idea.' when the judgment was made for an earlier idea", () => {
    const content = intentFile({
      readiness: readinessJudgment("An earlier version of the idea.", { verdict: "not-ready" }),
      scoutReport: null,
    });

    expect(content).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Not judged for this version of the idea.",
        "",
      ].join("\n"),
    );
  });

  it("notes that the project has changed since when the scout report is stale", () => {
    const content = intentFile({
      readiness: null,
      scoutReport: scoutReportFixture({ stale: true }),
    });

    expect(content).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Not judged for this version of the idea.",
        "",
        "## Project state",
        "",
        "- **Built:** The export bundle already writes decisions.md. (server/export.ts:17)",
        "- **Gap:** Nothing records why a bundle exists. (server/export-bundle.ts:1)",
        "",
        "- **Commit read:** abc123",
        "",
        "The project has changed since this report was read.",
        "",
      ].join("\n"),
    );
  });

  it("has no 'Project state' section when the session has never been scouted", () => {
    const content = intentFile({ readiness: readinessJudgment(IDEA), scoutReport: null });

    expect(content).toBe(
      [
        "# Intent: Grill Room",
        "",
        "## The original idea, before the interview",
        "",
        IDEA,
        "",
        "## Readiness before the interview",
        "",
        "Judged at 2026-09-01T00:00:00.000Z, on the idea as first written, before any question was asked.",
        "",
        "- **Objective:** Write intent.md into every export bundle.",
        "- **Expected outcome:** A reader of the repo can see why the feature exists without opening Grill Room.",
        "- **Verdict:** ready",
        "",
      ].join("\n"),
    );
    expect(content).not.toContain("## Project state");
  });

  describe("the spec's opening", () => {
    const GRILL_IDEA = "A local app that grills me about an idea until it is decided.";
    const notJudged = ["## Readiness before the interview", "", "Not judged for this version of the idea.", ""];

    function withSpec(specMarkdown: string): string {
      return intentFile({ idea: GRILL_IDEA, specMarkdown, readiness: null, scoutReport: null });
    }

    it("opens with the Problem Statement and the Solution, then the labelled idea", () => {
      expect(
        withSpec("## Problem Statement\n\nA settled idea.\n\n## Solution\n\nA workspace."),
      ).toBe(
        [
          "# Intent: Grill Room",
          "",
          "## Problem Statement",
          "",
          "A settled idea.",
          "",
          "## Solution",
          "",
          "A workspace.",
          "",
          "## The original idea, before the interview",
          "",
          GRILL_IDEA,
          "",
          ...notJudged,
        ].join("\n"),
      );
    });

    it("opens with the Problem Statement alone when the spec has no Solution", () => {
      expect(withSpec("## Problem Statement\n\nA settled idea.\n\n## User Stories\n\n1. U.")).toBe(
        [
          "# Intent: Grill Room",
          "",
          "## Problem Statement",
          "",
          "A settled idea.",
          "",
          "## The original idea, before the interview",
          "",
          GRILL_IDEA,
          "",
          ...notJudged,
        ].join("\n"),
      );
    });

    it("opens with the Solution alone when the spec has no Problem Statement", () => {
      expect(withSpec("## Solution\n\nA workspace.\n\n## User Stories\n\n1. U.")).toBe(
        [
          "# Intent: Grill Room",
          "",
          "## Solution",
          "",
          "A workspace.",
          "",
          "## The original idea, before the interview",
          "",
          GRILL_IDEA,
          "",
          ...notJudged,
        ].join("\n"),
      );
    });

    it("opens with the labelled idea alone when the spec has neither heading", () => {
      expect(withSpec("## Problem\n\nA spec.")).toBe(
        [
          "# Intent: Grill Room",
          "",
          "## The original idea, before the interview",
          "",
          GRILL_IDEA,
          "",
          ...notJudged,
        ].join("\n"),
      );
    });

    it("puts the Problem Statement first even when the spec has the Solution first", () => {
      expect(withSpec("## Solution\n\nA workspace.\n\n## Problem Statement\n\nA settled idea.")).toBe(
        [
          "# Intent: Grill Room",
          "",
          "## Problem Statement",
          "",
          "A settled idea.",
          "",
          "## Solution",
          "",
          "A workspace.",
          "",
          "## The original idea, before the interview",
          "",
          GRILL_IDEA,
          "",
          ...notJudged,
        ].join("\n"),
      );
    });
  });
});

describe("extractSpecSection", () => {
  const cases: { name: string; spec: string[] | string; ps: string | null; sol: string | null }[] = [
    {
      name: "both sections, each ended by the next level-2 heading",
      spec: ["## Problem Statement", "", "P.", "", "## Solution", "", "S.", "", "## User Stories", "", "1. U."],
      ps: "P.",
      sol: "S.",
    },
    { name: "a heading in the wrong case", spec: ["## problem statement", "", "P."], ps: null, sol: null },
    { name: "surrounding spaces around the heading", spec: ["   ## Problem Statement   ", "P."], ps: "P.", sol: null },
    { name: "a heading with a trailing colon", spec: ["## Problem Statement:", "P."], ps: null, sol: null },
    { name: "no space after ##", spec: ["##Problem Statement", "P."], ps: null, sol: null },
    { name: "two spaces inside the name", spec: ["## Problem  Statement", "P."], ps: null, sol: null },
    { name: "a level-3 heading", spec: ["### Problem Statement", "P."], ps: null, sol: null },
    { name: "a level-1 heading", spec: ["# Problem Statement", "P."], ps: null, sol: null },
    {
      name: "a level-3 heading inside the section does not end it",
      spec: ["## Problem Statement", "P.", "### Detail", "D.", "## Solution", "S."],
      ps: "P.\n### Detail\nD.",
      sol: "S.",
    },
    {
      name: "a level-1 heading ends the section too",
      spec: ["## Problem Statement", "P.", "# Appendix", "A."],
      ps: "P.",
      sol: null,
    },
    {
      name: "the last section runs to the end",
      spec: ["## Solution", "S.", "", "## Problem Statement", "P."],
      ps: "P.",
      sol: "S.",
    },
    {
      name: "the first heading wins",
      spec: ["## Problem Statement", "First.", "## Problem Statement", "Second."],
      ps: "First.",
      sol: null,
    },
    {
      name: "a body of only blank lines counts as missing",
      spec: ["## Problem Statement", "", "   ", "## Solution", "S."],
      ps: null,
      sol: "S.",
    },
    {
      name: "CRLF line endings come back as LF",
      spec: "## Problem Statement\r\n\r\nP line 1.\r\nP line 2.\r\n",
      ps: "P line 1.\nP line 2.",
      sol: null,
    },
    {
      name: "inner blank lines and indentation are kept",
      spec: ["## Problem Statement", "", "    indented", "", "middle", "", ""],
      ps: "    indented\n\nmiddle",
      sol: null,
    },
    { name: "an empty spec", spec: "", ps: null, sol: null },
  ];

  for (const { name, spec, ps, sol } of cases) {
    it(name, () => {
      const markdown = typeof spec === "string" ? spec : spec.join("\n");
      expect(extractSpecSection(markdown, "Problem Statement")).toBe(ps);
      expect(extractSpecSection(markdown, "Solution")).toBe(sol);
    });
  }
});

describe("the export manifest", () => {
  const sha = (text: string) => createHash("sha256").update(text, "utf8").digest("hex");

  function planned(relativePath: string, content: string, kept = false) {
    return { relativePath, content, kept };
  }

  const durableRoot = { root: "durable", otherRootFolder: ".grill-room/a" } as const;

  it("records the session, revision 1, its root, the other root's folder, both commits and a hash per written file, with no timestamps", () => {
    const manifest = buildExportManifest({
      sessionId: "session-1",
      ...durableRoot,
      previous: null,
      scoutCommit: "abc123",
      headCommit: "def456",
      planned: [planned("spec.md", "# Spec\n"), planned("intent.md", "# Intent\n")],
      keptRemovals: [],
    });

    expect(renderExportManifest(manifest)).toBe(
      [
        "{",
        '  "version": 3,',
        '  "sessionId": "session-1",',
        '  "revision": 1,',
        '  "root": "durable",',
        '  "otherRootFolder": ".grill-room/a",',
        '  "scoutCommit": "abc123",',
        '  "headCommit": "def456",',
        '  "files": [',
        "    {",
        '      "path": "spec.md",',
        `      "sha256": "${sha("# Spec\n")}"`,
        "    },",
        "    {",
        '      "path": "intent.md",',
        `      "sha256": "${sha("# Intent\n")}"`,
        "    }",
        "  ]",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("records null commits outside a repository and without a scout report", () => {
    const manifest = buildExportManifest({
      sessionId: "session-1",
      root: "working",
      otherRootFolder: "docs/specs/a",
      previous: null,
      scoutCommit: null,
      headCommit: null,
      planned: [],
      keptRemovals: [],
    });
    expect(manifest).toEqual({
      version: 3,
      sessionId: "session-1",
      revision: 1,
      root: "working",
      otherRootFolder: "docs/specs/a",
      scoutCommit: null,
      headCommit: null,
      files: [],
    });
  });

  it("numbers revisions one past the previous manifest's, counting a version-1 manifest as 0", () => {
    const base = {
      sessionId: "s",
      ...durableRoot,
      scoutCommit: null,
      headCommit: null,
      planned: [],
      keptRemovals: [],
    };

    const v1 = parseExportManifest(JSON.stringify({ version: 1, files: ["spec.md"] }));
    expect(v1?.revision).toBe(0);
    expect(buildExportManifest({ ...base, previous: v1 }).revision).toBe(1);

    const first = buildExportManifest({ ...base, previous: null });
    const second = buildExportManifest({
      ...base,
      previous: parseExportManifest(renderExportManifest(first)),
    });
    const third = buildExportManifest({
      ...base,
      previous: parseExportManifest(renderExportManifest(second)),
    });
    expect([first.revision, second.revision, third.revision]).toEqual([1, 2, 3]);
  });

  it("hashes content with CRLF normalised to LF", () => {
    expect(hashExportContent("a\r\nb\r\n")).toBe(hashExportContent("a\nb\n"));
    expect(hashExportContent("a\nb\n")).toBe(sha("a\nb\n"));
    expect(hashExportContent("a\nb\n")).not.toBe(hashExportContent("a\nb"));
  });

  it("keeps a kept file's previous hash, and leaves out a kept file it never hashed", () => {
    const previous = parseExportManifest(
      JSON.stringify({
        version: 2,
        sessionId: "s",
        revision: 4,
        scoutCommit: null,
        headCommit: null,
        files: [
          { path: "spec.md", sha256: sha("old spec") },
          { path: "issues/02-old.md", sha256: sha("old ticket") },
        ],
      }),
    );

    const manifest = buildExportManifest({
      sessionId: "s",
      ...durableRoot,
      previous,
      scoutCommit: null,
      headCommit: null,
      planned: [
        planned("spec.md", "new spec", true),
        planned("intent.md", "new intent", true),
        planned("decisions.md", "decisions"),
      ],
      keptRemovals: ["issues/02-old.md"],
    });

    expect(manifest.revision).toBe(5);
    expect(manifest.files).toEqual([
      { path: "spec.md", sha256: sha("old spec") },
      { path: "decisions.md", sha256: sha("decisions") },
      { path: "issues/02-old.md", sha256: sha("old ticket") },
    ]);
  });

  it("parses all three versions and refuses anything malformed", () => {
    expect(parseExportManifest(JSON.stringify({ version: 1, files: ["a.md"] }))).toEqual({
      version: 1,
      sessionId: null,
      revision: 0,
      scoutCommit: null,
      headCommit: null,
      files: [{ path: "a.md", sha256: null }],
    });

    // A version-2 manifest as a pre-split export wrote it parses exactly as
    // before: no root, no other root's folder.
    const v2 = {
      version: 2,
      sessionId: "s",
      revision: 2,
      scoutCommit: "c",
      headCommit: null,
      files: [{ path: "a.md", sha256: sha("a") }],
    };
    expect(parseExportManifest(`${JSON.stringify(v2, null, 2)}\n`)).toEqual(v2);

    const v3 = buildExportManifest({
      sessionId: "s",
      ...durableRoot,
      previous: null,
      scoutCommit: "c",
      headCommit: null,
      planned: [planned("a.md", "a")],
      keptRemovals: [],
    });
    expect(parseExportManifest(renderExportManifest(v3))).toEqual(v3);

    for (const malformed of [
      "{ not json",
      JSON.stringify({ version: 1 }),
      JSON.stringify({ version: 1, files: ["a.md", 7] }),
      JSON.stringify({ version: 3, files: [] }),
      JSON.stringify({ ...v2, version: 4 }),
      JSON.stringify({ ...v3, version: 4 }),
      JSON.stringify({ ...v2, files: [{ path: "a.md", sha256: "not-a-hash" }] }),
      JSON.stringify({ ...v2, files: ["a.md"] }),
      JSON.stringify({ ...v2, revision: 0 }),
      JSON.stringify({ ...v2, sessionId: 7 }),
      JSON.stringify({ ...v3, root: "elsewhere" }),
      JSON.stringify({ ...v3, root: undefined }),
      JSON.stringify({ ...v3, otherRootFolder: 7 }),
      JSON.stringify({ ...v3, files: [{ path: "a.md", sha256: "not-a-hash" }] }),
    ]) {
      expect(parseExportManifest(malformed)).toBeNull();
    }
  });
});

describe("planExport: an own answer restated", () => {
  useTestDatabase();

  const ORIGINAL = "Stirpe. Claude, double-check the fee table.";
  const NOTES = "Claude, double-check the fee table.";

  async function aSessionWithARestatement() {
    const session = await createSession.run({
      title: "Grill Room",
      idea: "A marketplace for local services.",
    });
    const now = new Date().toISOString();
    await getDb().insert(schema.decisions).values({
      id: "d-provider",
      sessionId: session.id,
      key: "provider",
      questionTitle: "Which payment provider handles payouts?",
      questionBody: "",
      offeredChoicesJson: "[]",
      dependsOnJson: "[]",
      introducedBy: "interviewer",
      answerKind: "own-answer",
      currentAnswer: ORIGINAL,
      settledAt: "2026-09-01T00:00:01.000Z",
      restatementText: "Stripe.",
      restatementNotes: NOTES,
      restatementReason: "Took out a note to the AI.",
      createdAt: now,
      updatedAt: now,
    });
    return session;
  }

  async function exportedFiles(sessionId: string) {
    const rows = await getDb()
      .select()
      .from(schema.decisions)
      .where(eq(schema.decisions.sessionId, sessionId));
    return planExport({
      sessionTitle: "Grill Room",
      idea: "A marketplace for local services.",
      specMarkdown: "## Problem\n\nA spec.",
      tickets: [],
      decisions: describeDecisions(rows),
      readiness: null,
      scoutReport: null,
    }).files;
  }

  it("changes nothing in decisions.md while the restatement is only proposed", async () => {
    const session = await aSessionWithARestatement();

    const decisions = (await exportedFiles(session.id)).find(
      (file) => file.relativePath === "decisions.md",
    )!;

    expect(decisions.content).toContain(ORIGINAL);
    expect(decisions.content).not.toContain("Took out a note");
  });

  it("shows the accepted statement, and no exported file carries the operator notes", async () => {
    const session = await aSessionWithARestatement();

    await acceptRestatement.run({ decisionId: "d-provider" });
    const files = await exportedFiles(session.id);

    const decisions = files.find((file) => file.relativePath === "decisions.md")!;
    expect(decisions.content).toContain("Which payment provider handles payouts?");
    expect(decisions.content).toContain("Stripe.");
    expect(decisions.content).not.toContain("Stirpe");
    for (const file of files) {
      expect(file.content, file.relativePath).not.toContain(NOTES);
    }
    // The notes are kept, in the app's own history.
    const [entry] = await getDb()
      .select()
      .from(schema.decisionHistory)
      .where(eq(schema.decisionHistory.decisionId, "d-provider"));
    expect(entry).toMatchObject({ answer: ORIGINAL, operatorNotes: NOTES });
  });
});

describe("planExport: a gate's ticket file", () => {
  const ACCOUNT = "A live account on the payment platform, with API keys issued.";

  function ticketFiles() {
    return planExport({
      sessionTitle: "Grill Room",
      idea: "An idea.",
      specMarkdown: "## Problem\n\nA spec.",
      tickets: [
        { number: 1, slug: "build-the-workspace", title: "Build the workspace", body: "Build it.", blockedBy: [] },
        {
          number: 2,
          slug: "payment-account",
          title: "Payment account is live",
          body: "The owner opens the account; it is in place once API keys are issued.",
          blockedBy: [1],
          kind: "gate",
          waitsFor: ACCOUNT,
        },
        { number: 3, slug: "store-on-disk", title: "Store on disk", body: "Store it.", blockedBy: [2, 1], kind: "build", waitsFor: null },
      ],
      decisions: [],
      readiness: null,
      scoutReport: null,
    }).files.filter((file) => file.relativePath.startsWith("issues/"));
  }

  it("gives a gate a ready-for-human status and a Wait for line", () => {
    expect(ticketFiles().find((file) => file.relativePath === "issues/02-payment-account.md")?.content).toBe(
      `# 02 Payment account is live\n\nStatus: ready-for-human\nBlocked by: 01\nWait for: ${ACCOUNT}\n\nThe owner opens the account; it is in place once API keys are issued.`,
    );
  });

  it("leaves a build ticket's file as it was", () => {
    expect(ticketFiles().map((file) => [file.relativePath, file.content])).toEqual([
      ["issues/01-build-the-workspace.md", "# 01 Build the workspace\n\nStatus: ready-for-agent\nBlocked by: none\n\nBuild it."],
      expect.anything(),
      ["issues/03-store-on-disk.md", "# 03 Store on disk\n\nStatus: ready-for-agent\nBlocked by: 01, 02\n\nStore it."],
    ]);
  });
});

describe("planExport: a ticket's Implements line", () => {
  const ACCOUNT = "A live account on the payment platform, with API keys issued.";

  function fileFor(ticket: {
    kind?: "build" | "gate";
    waitsFor?: string | null;
    implements?: readonly number[] | null;
  }): string {
    const tickets = [
      {
        number: 1,
        slug: "build-the-workspace",
        title: "Build the workspace",
        body: "Build it.",
        blockedBy: [],
        ...ticket,
      },
    ];
    return planExport({
      sessionTitle: "Grill Room",
      idea: "An idea.",
      specMarkdown: "## Problem\n\nA spec.",
      tickets,
      decisions: [],
      readiness: null,
      scoutReport: null,
    }).files.find((file) => file.relativePath === "issues/01-build-the-workspace.md")!.content;
  }

  it.each([
    ["one story", [3], "Implements: user story 3"],
    ["several stories, as ranges", [5, 2, 3], "Implements: user stories 2-3, 5"],
  ])("writes %s after Blocked by", (_, implementsList, line) => {
    expect(fileFor({ implements: implementsList })).toBe(
      `# 01 Build the workspace\n\nStatus: ready-for-agent\nBlocked by: none\n${line}\n\nBuild it.`,
    );
  });

  it("writes it after a gate's Wait for line", () => {
    expect(fileFor({ kind: "gate", waitsFor: ACCOUNT, implements: [3] })).toBe(
      `# 01 Build the workspace\n\nStatus: ready-for-human\nBlocked by: none\nWait for: ${ACCOUNT}\nImplements: user story 3\n\nBuild it.`,
    );
  });

  it.each([
    ["empty", []],
    ["null", null],
    ["absent", undefined],
  ] as const)("writes no line when implements is %s", (_, implementsList) => {
    expect(fileFor(implementsList === undefined ? {} : { implements: implementsList })).toBe(
      "# 01 Build the workspace\n\nStatus: ready-for-agent\nBlocked by: none\n\nBuild it.",
    );
  });
});

describe("planExport: decisions.md ADR marks", () => {
  type Convention = NonNullable<ScoutReportWithStaleness["facts"]["adrConvention"]>;

  function convention(folder: string, prefix: string): Convention {
    return {
      folder,
      numbering: { prefix, width: 3, nextNumber: `${prefix}013`, example: `${prefix}012-x.md` },
      template: null,
    };
  }

  function render(
    decisions: readonly DecisionView[],
    adrConvention: Convention | null,
    withScoutReport = true,
  ): string | undefined {
    const report = scoutReportFixture();
    const scoutReport = withScoutReport ? { ...report, facts: { ...report.facts, adrConvention } } : null;
    const plan = planExport({
      sessionTitle: "Grill Room",
      idea: "An idea.",
      specMarkdown: "## Problem\n\nA spec.",
      tickets: [],
      decisions,
      readiness: null,
      scoutReport,
    });
    return plan.files.find((file) => file.relativePath === "decisions.md")?.content;
  }

  function entryOf(content: string | undefined, key: string): string {
    const start = content!.indexOf(`<a id="${key}"></a>`);
    const rest = content!.slice(start);
    const end = rest.search(/\n\n(?:<a id=|## )/);
    return end === -1 ? rest.trimEnd() : rest.slice(0, end);
  }

  function reopened(key: string, citation: string, overrides: Partial<DecisionView> = {}) {
    return decision(key, {
      introducedBy: "repo",
      repo: { source: "recorded", citation, statement: `Statement of ${key}`, scoutReportId: "report-1" },
      ...overrides,
    });
  }

  function replacedByE(): Partial<DecisionView> {
    return { replacedBy: { id: "id-e", key: "e", title: "Title of e", reason: "r" } };
  }

  function flaggedE(overrides: Partial<DecisionView> = {}) {
    return decision("e", { adrWorthy: true, consequences: "Commits us.", ...overrides });
  }

  function eText(...adrLines: string[]): string {
    return [
      '<a id="e"></a>',
      "### Title of e",
      "",
      "- **Decision:** Answer of e",
      "- **Origin:** interviewer · accepted recommendation",
      ...adrLines,
    ].join("\n");
  }

  const NMON = convention("docs/adr", "NMON-");
  const BARE = convention("docs/adr", "");
  const CONS = "- **Consequences:** Commits us.";

  const rows: {
    name: string;
    citations: string[];
    convention: Convention | null;
    amends: string | null;
  }[] = [
    { name: "a numbered ADR", citations: ["docs/adr/NMON-012-read-model.md:4"], convention: NMON, amends: "NMON-012 (docs/adr/NMON-012-read-model.md)" },
    { name: "a citation without a line", citations: ["CLAUDE.md"], convention: NMON, amends: "CLAUDE.md" },
    { name: "an empty citation", citations: [""], convention: NMON, amends: null },
    { name: "a dated name", citations: ["docs/adr/2024-01-05-x.md:1"], convention: BARE, amends: "docs/adr/2024-01-05-x.md" },
    { name: "a template name", citations: ["docs/adr/0000-template.md:1"], convention: BARE, amends: "docs/adr/0000-template.md" },
    { name: "a prefix whose case differs", citations: ["docs/adr/nmon-012-x.md:1"], convention: NMON, amends: "docs/adr/nmon-012-x.md" },
    { name: "a line range", citations: ["docs/adr/0007-queue.md:1-9"], convention: BARE, amends: "0007 (docs/adr/0007-queue.md)" },
    { name: "no convention", citations: ["docs/adr/NMON-012-read-model.md:4"], convention: null, amends: "docs/adr/NMON-012-read-model.md" },
    { name: "a path outside the folder", citations: ["CLAUDE.md:12"], convention: NMON, amends: "CLAUDE.md" },
    { name: "a name that does not match", citations: ["docs/adr/notes.md:3"], convention: NMON, amends: "docs/adr/notes.md" },
    { name: "a different prefix", citations: ["docs/adr/0007-queue.md:2"], convention: NMON, amends: "docs/adr/0007-queue.md" },
    {
      name: "two replaced decisions in tree order",
      citations: ["docs/adr/NMON-012-a.md:4", ".claude/rules/x.md:3"],
      convention: NMON,
      amends: "NMON-012 (docs/adr/NMON-012-a.md), .claude/rules/x.md",
    },
    {
      name: "two replaced decisions citing one file",
      citations: ["docs/adr/NMON-012-a.md:4", "docs/adr/NMON-012-a.md:30"],
      convention: NMON,
      amends: "NMON-012 (docs/adr/NMON-012-a.md)",
    },
  ];

  describe("decisions.md: an ADR-worthy entry's Amends line", () => {
    for (const row of rows) {
      it(row.name, () => {
        const replaced = row.citations.map((citation, index) =>
          reopened(`r${index + 1}`, citation, replacedByE()),
        );
        const content = render([...replaced, flaggedE()], row.convention);
        const expected = eText(
          "- **ADR-worthy:** yes",
          ...(row.amends === null ? [] : [`- **Amends:** ${row.amends}`]),
          CONS,
        );
        expect(entryOf(content, "e")).toBe(expected);
      });
    }

    it("flagged, replacing nothing: no Amends line", () => {
      expect(entryOf(render([flaggedE()], NMON), "e")).toBe(eText("- **ADR-worthy:** yes", CONS));
    });

    it("flagged, replacing a decision that is not a repo decision: no Amends line", () => {
      const other = decision("o", replacedByE());
      expect(entryOf(render([other, flaggedE()], NMON), "e")).toBe(eText("- **ADR-worthy:** yes", CONS));
    });

    it("unflagged, replacing a repo decision: no ADR fields", () => {
      const r = reopened("r1", "docs/adr/NMON-012-a.md:4", replacedByE());
      expect(entryOf(render([r, flaggedE({ adrWorthy: false })], NMON), "e")).toBe(eText());
    });

    it("a flagged reopened repo decision amends its own citation", () => {
      const own = reopened("e", "docs/adr/NMON-003-x.md:2", { adrWorthy: true, consequences: "Commits us." });
      expect(entryOf(render([own], NMON), "e")).toContain(
        "- **Amends:** NMON-003 (docs/adr/NMON-003-x.md)\n- **Consequences:** Commits us.",
      );
    });

    it("a flagged decision later replaced by a flagged one carries no ADR fields, the replacer does", () => {
      const r = reopened("r1", "docs/adr/NMON-003-x.md:2", {
        adrWorthy: true,
        consequences: "Old.",
        ...replacedByE(),
      });
      const content = render([r, flaggedE()], NMON);
      expect(entryOf(content, "r1")).not.toContain("ADR-worthy");
      expect(entryOf(content, "r1")).not.toContain("Old.");
      expect(entryOf(content, "e")).toBe(
        eText("- **ADR-worthy:** yes", "- **Amends:** NMON-003 (docs/adr/NMON-003-x.md)", CONS),
      );
    });
  });

  it("decisions.md: an ADR-worthy entry ends with ADR-worthy, Amends and Consequences", () => {
    const own = reopened("e", "docs/adr/NMON-003-x.md:2", {
      answer: { text: "Own answer.", kind: "own-answer" },
      adrWorthy: true,
      consequences: "  Commits us to X.\n\nRules out Y.  ",
    });
    expect(entryOf(render([own], NMON), "e")).toBe(
      [
        '<a id="e"></a>',
        "### Title of e",
        "",
        "- **Decision:** Own answer.",
        "- **Origin:** repo (recorded) · reopened",
        "- **Source:** docs/adr/NMON-003-x.md:2",
        '- **Supersedes:** "Statement of e"',
        "- **ADR-worthy:** yes",
        "- **Amends:** NMON-003 (docs/adr/NMON-003-x.md)",
        "- **Consequences:** Commits us to X.",
        "  ",
        "  Rules out Y.",
      ].join("\n"),
    );
  });

  it("decisions.md: an unflagged entry renders as before, whatever its consequences hold", () => {
    const withText = render([decision("e", { adrWorthy: false, consequences: "X." })], NMON);
    const without = render([decision("e", { adrWorthy: false, consequences: null })], NMON);
    expect(withText).toBe(without);
    expect(withText).not.toContain("ADR-worthy");
  });

  it("decisions.md: a flagged kept repo decision is marked under Built under", () => {
    const kept = {
      ...keptRepo("queue-choice", "docs/decisions.md:12"),
      adrWorthy: true,
      consequences: "  Commits us to X.\n\nRules out Y.  ",
    };
    const content = render([decision("storage"), kept, keptRepo("zplain", "a.md:1")], NMON)!;
    expect(content.slice(content.indexOf("## Built under"))).toBe(
      [
        "## Built under",
        "",
        "- `queue-choice`: docs/decisions.md:12 · ADR-worthy",
        "  Consequences: Commits us to X.",
        "  ",
        "  Rules out Y.",
        "- `zplain`: a.md:1",
        "",
      ].join("\n"),
    );
    const alone = { ...keptRepo("queue-choice", "docs/decisions.md:12"), adrWorthy: true, consequences: "X." };
    expect(render([alone], NMON)).toBeUndefined();
  });

  it("planExport passes the scout report's ADR convention to decisions.md", () => {
    const r = reopened("r1", "docs/adr/NMON-012-read-model.md:4", replacedByE());
    const decisions = [r, flaggedE()];
    expect(entryOf(render(decisions, NMON), "e")).toContain(
      "- **Amends:** NMON-012 (docs/adr/NMON-012-read-model.md)\n",
    );
    expect(entryOf(render(decisions, NMON, false), "e")).toContain(
      "- **Amends:** docs/adr/NMON-012-read-model.md\n",
    );
  });
});
