import { describe, expect, it } from "vitest";

import { planExport } from "./export.js";
import type { DecisionView } from "./tree.js";

let counter = 0;

/** A settled interviewer decision answered with its recommendation, unless told otherwise. */
function decision(key: string, overrides: Partial<DecisionView> = {}): DecisionView {
  counter += 1;
  return {
    id: `id-${key}`,
    key,
    questionTitle: `Title of ${key}`,
    questionBody: `The question behind ${key}, which never reaches decisions.md.`,
    choices: [],
    recommendedChoice: null,
    recommendedChoiceLabel: null,
    recommendedAnswer: `Answer of ${key}`,
    dependsOn: [],
    introducedBy: "interviewer",
    repo: null,
    state: "settled",
    answer: { text: `Answer of ${key}`, kind: "accepted-recommendation" },
    supersession: null,
    dispositionTarget: null,
    settledAt: "2026-09-01T00:00:00.000Z",
    reopenedAt: null,
    withdrawnAt: null,
    awaitingPlacementSince: null,
    createdAt: `2026-09-01T00:00:${String(counter % 60).padStart(2, "0")}.000Z`,
    ...overrides,
  };
}

function keptRepo(key: string, citation: string, source: "recorded" | "inferred" = "recorded") {
  return decision(key, {
    introducedBy: "repo",
    answer: { text: `Statement of ${key}`, kind: "repo-established" },
    repo: { source, citation, statement: `Statement of ${key}`, scoutReportId: "report-1" },
  });
}

function outOfScope(key: string, note: string, overrides: Partial<DecisionView> = {}) {
  return decision(key, {
    answer: { text: note, kind: "dispositioned" },
    dispositionTarget: "out-of-scope",
    ...overrides,
  });
}

function openQuestion(key: string) {
  return decision(key, {
    answer: { text: "Revisit once usage data exists.", kind: "dispositioned" },
    dispositionTarget: "open-question",
  });
}

function decisionsFile(decisions: readonly DecisionView[], sessionTitle = "Grill Room"): string | undefined {
  const plan = planExport({ sessionTitle, specMarkdown: "## Problem\n\nA spec.", tickets: [], decisions });
  return plan.files.find((file) => file.relativePath === "decisions.md")?.content;
}

const CHOICES = [
  { label: "SQLite", rationale: "One file, no server to run." },
  { label: "Postgres", rationale: "Scales, but needs a server." },
];

describe("planExport: decisions.md", () => {
  it("renders the full file: header, entries with origin labels and the why, out of scope and built under", () => {
    const content = decisionsFile([
      keptRepo("repo-stack", "AGENTS.md:12"),
      decision("storage", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite",
        answer: { text: "SQLite", kind: "accepted-recommendation" },
        dependsOn: ["id-repo-stack"],
      }),
      decision("hosting", {
        choices: CHOICES,
        recommendedChoice: 0,
        answer: { text: "Postgres", kind: "own-answer" },
        dependsOn: ["id-storage", "id-metrics"],
      }),
      openQuestion("metrics"),
      decision("naming", {
        introducedBy: "user",
        choices: CHOICES,
        answer: { text: "Call it Grill Room,\nnot Grillr.", kind: "own-answer" },
        dependsOn: ["id-storage"],
      }),
      outOfScope("mobile", "Desktop only for now."),
    ]);

    expect(content).toBe(
      [
        "# Decisions: Grill Room",
        "",
        "Generated by the Grill Room export from this session's settled design tree.",
        "",
        "## Decisions",
        "",
        '<a id="storage"></a>',
        "### Title of storage",
        "",
        "- **Decision:** SQLite",
        "- **Why (interviewer's case):** One file, no server to run.",
        "- **Origin:** interviewer · accepted recommendation",
        "- **Depends on:** `repo-stack` (AGENTS.md:12)",
        "",
        '<a id="hosting"></a>',
        "### Title of hosting",
        "",
        "- **Decision:** Postgres",
        "- **Why (interviewer's case):** Scales, but needs a server.",
        "- **Origin:** interviewer · another offered option",
        "- **Depends on:** Title of metrics (open question, see spec), [Title of storage](#storage)",
        "",
        '<a id="naming"></a>',
        "### Title of naming",
        "",
        "- **Decision:** Call it Grill Room,",
        "  not Grillr.",
        "- **Origin:** user · own answer",
        "- **Depends on:** [Title of storage](#storage)",
        "",
        "## Out of scope",
        "",
        "- **Title of mobile**: Desktop only for now.",
        "",
        "## Built under",
        "",
        "- `repo-stack`: AGENTS.md:12",
        "",
      ].join("\n"),
    );
  });

  it("renders an accepted recommendation with a choice index as that choice, its case and the interviewer's note", () => {
    const content = decisionsFile([
      decision("accepted", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite, because one file is enough.",
        answer: { text: "SQLite, because one file is enough.", kind: "accepted-recommendation" },
      }),
      decision("same", {
        choices: CHOICES,
        recommendedChoice: 1,
        recommendedAnswer: "Postgres",
        answer: { text: "Postgres", kind: "accepted-recommendation" },
      }),
    ])!;

    expect(content).toContain(
      [
        '<a id="accepted"></a>',
        "### Title of accepted",
        "",
        "- **Decision:** SQLite",
        "- **Why (interviewer's case):** One file, no server to run.",
        "- **Recommendation note (interviewer's):** SQLite, because one file is enough.",
        "- **Origin:** interviewer · accepted recommendation",
      ].join("\n"),
    );
    // A note that only repeats the label adds nothing and is left out.
    expect(content).toContain(
      [
        "- **Decision:** Postgres",
        "- **Why (interviewer's case):** Scales, but needs a server.",
        "- **Origin:** interviewer · accepted recommendation",
      ].join("\n"),
    );
    expect(content.match(/Recommendation note/g)).toHaveLength(1);
  });

  it("renders an accepted recommendation without a choice index as its answer, with a why only on a text match", () => {
    const content = decisionsFile([
      decision("no-index", {
        choices: CHOICES,
        recommendedChoice: null,
        recommendedAnswer: "Keep it in memory.",
        answer: { text: "Keep it in memory.", kind: "accepted-recommendation" },
      }),
      decision("no-choices", {
        recommendedChoice: 0,
        answer: { text: "Ship weekly.", kind: "accepted-recommendation" },
      }),
      decision("matched", {
        choices: CHOICES,
        recommendedChoice: null,
        answer: { text: "SQLite", kind: "accepted-recommendation" },
      }),
    ])!;

    expect(content).toContain(
      "- **Decision:** Keep it in memory.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).toContain(
      "- **Decision:** Ship weekly.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).toContain(
      "- **Decision:** SQLite\n- **Why (interviewer's case):** One file, no server to run.\n- **Origin:** interviewer · accepted recommendation",
    );
    expect(content).not.toContain("Recommendation note");
  });

  it("labels an own answer that matches an offered choice as another offered option, with its case", () => {
    const content = decisionsFile([
      decision("picked", {
        choices: CHOICES,
        recommendedChoice: 0,
        recommendedAnswer: "SQLite, because one file is enough.",
        answer: { text: "Postgres", kind: "own-answer" },
      }),
      decision("typed", { choices: CHOICES, answer: { text: "Flat JSON files", kind: "own-answer" } }),
    ])!;

    expect(content).toContain(
      "- **Decision:** Postgres\n- **Why (interviewer's case):** Scales, but needs a server.\n- **Origin:** interviewer · another offered option",
    );
    expect(content).toContain("- **Decision:** Flat JSON files\n- **Origin:** interviewer · own answer");
    expect(content).not.toContain("Recommendation note");
    expect(content).not.toContain("SQLite, because");
  });

  it("writes a reopened repo decision as a full entry with its source and a Supersedes line", () => {
    const content = decisionsFile([
      decision("repo-db", {
        introducedBy: "repo",
        answer: { text: "Move to Postgres.", kind: "own-answer" },
        repo: {
          source: "inferred",
          citation: "server/db/index.ts:4",
          statement: "The app stores\nits data in SQLite.",
          scoutReportId: "report-1",
        },
      }),
    ]);

    expect(content).toContain(
      [
        '<a id="repo-db"></a>',
        "### Title of repo-db",
        "",
        "- **Decision:** Move to Postgres.",
        "- **Origin:** repo (inferred) · reopened",
        "- **Source:** server/db/index.ts:4",
        '- **Supersedes:** "The app stores its data in SQLite."',
      ].join("\n"),
    );
    expect(content).not.toContain("## Built under");

    const recorded = decisionsFile([
      decision("repo-db", {
        introducedBy: "repo",
        answer: { text: "Move to Postgres.", kind: "accepted-recommendation" },
        repo: { source: "recorded", citation: "docs/adr/0001.md:3", statement: "SQLite.", scoutReportId: null },
      }),
    ]);
    expect(recorded).toContain("- **Origin:** repo (recorded) · reopened");
  });

  it("lists a kept repo decision only under Built under, as key and citation, never restated", () => {
    const content = decisionsFile([keptRepo("repo-stack", "AGENTS.md:12"), decision("storage")])!;

    expect(content).toContain("## Built under\n\n- `repo-stack`: AGENTS.md:12\n");
    expect(content).not.toContain("Statement of repo-stack");
    expect(content).not.toContain('id="repo-stack"');
    expect(content).not.toContain("Title of repo-stack");
  });

  it("leaves out loose ends, open questions, and anything not settled, withdrawn or unplaced", () => {
    const left = [
      decision("unknown", { state: "frontier", answer: { text: "", kind: "unknown" } }),
      decision("pushed", { state: "frontier", answer: { text: "Wrong question", kind: "pushed-back" } }),
      decision("deferred", { state: "frontier", answer: { text: "", kind: "deferred" } }),
      decision("prototype", { state: "frontier", answer: { text: "Try it", kind: "prototype-flagged" } }),
      decision("never", { state: "frontier", answer: null }),
      decision("blocked", { state: "blocked", answer: null, dependsOn: ["id-never"] }),
      decision("stale", { state: "stale" }),
      decision("withdrawn", { state: "withdrawn" }),
      decision("unplaced", { state: "unplaced", introducedBy: "user", answer: null }),
      openQuestion("question"),
      outOfScope("stale-scope", "Stale note", { state: "stale" }),
    ];

    const content = decisionsFile([decision("kept"), ...left])!;

    for (const excluded of left) {
      expect(content).not.toContain(excluded.questionTitle);
    }
    expect(content).not.toContain("Revisit once usage data exists.");
    expect(content).not.toContain("## Out of scope");
    expect(content).toContain('<a id="kept"></a>');
    // A dropped repo decision never enters the tree, so it has nothing to render from.
  });

  it("orders every section topologically, prerequisites first, with ties broken by key", () => {
    const tree = [
      decision("zeta"),
      decision("alpha", { dependsOn: ["id-zeta"] }),
      decision("beta"),
      decision("gamma", { dependsOn: ["id-alpha", "id-beta"] }),
      outOfScope("z-scope", "Later."),
      outOfScope("a-scope", "Never.", { dependsOn: ["id-z-scope"] }),
      outOfScope("m-scope", "Not now."),
      keptRepo("repo-b", "b.md:1"),
      keptRepo("repo-a", "a.md:1"),
    ];

    const content = decisionsFile(tree)!;
    const anchors = [...content.matchAll(/<a id="([^"]+)"><\/a>/g)].map((match) => match[1]);
    expect(anchors).toEqual(["beta", "zeta", "alpha", "gamma"]);
    expect(content).toContain(
      "## Out of scope\n\n- **Title of m-scope**: Not now.\n- **Title of z-scope**: Later.\n- **Title of a-scope**: Never.\n",
    );
    expect(content).toContain("## Built under\n\n- `repo-a`: a.md:1\n- `repo-b`: b.md:1\n");

    expect(decisionsFile(tree)).toBe(content);
    expect(decisionsFile([...tree].reverse())).toBe(content);
  });

  it("links dependencies only to entries, and names out-of-scope ones in plain text", () => {
    const content = decisionsFile([
      outOfScope("mobile", "Desktop only."),
      decision("ui", { dependsOn: ["id-mobile", "id-gone", "id-missing"] }),
      decision("gone", { state: "withdrawn" }),
    ])!;

    expect(content).toContain("- **Depends on:** Title of mobile (out of scope)\n");
    expect(content).not.toContain("Title of gone");
    expect(content).not.toContain("](#mobile)");
  });

  it("plans decisions.md beside the spec with one entry, or with one out-of-scope item alone", () => {
    const withEntry = planExport({
      sessionTitle: "Grill Room",
      specMarkdown: "A spec.",
      tickets: [{ number: 1, slug: "first", title: "First", body: "Body", blockedBy: [] }],
      decisions: [decision("only")],
    });
    expect(withEntry.files.map((file) => file.relativePath)).toEqual([
      "spec.md",
      "decisions.md",
      "issues/01-first.md",
    ]);

    const scopeOnly = decisionsFile([outOfScope("mobile", "")])!;
    expect(scopeOnly).toBe(
      [
        "# Decisions: Grill Room",
        "",
        "Generated by the Grill Room export from this session's settled design tree.",
        "",
        "## Out of scope",
        "",
        "- **Title of mobile**",
        "",
      ].join("\n"),
    );
    expect(scopeOnly).not.toContain("## Decisions\n");
  });

  it("does not plan decisions.md with only Built under, or with nothing", () => {
    expect(decisionsFile([keptRepo("repo-stack", "AGENTS.md:12")])).toBeUndefined();
    expect(decisionsFile([openQuestion("question")])).toBeUndefined();
    expect(decisionsFile([])).toBeUndefined();
  });
});
